// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
	"uuid"
)

type IdentityUser struct {
	ID             uuid.UUID
	AuthProvider   string
	AuthProviderID string
	Email          string
	Role           string
	Status         string
	KycStatus      string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}
