// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package repository

import (
	"context"

	"uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO identity.users (id, auth_provider, auth_provider_id, email, role, status, kyc_status)
VALUES ($1, $2, $3, $4, $5, $6, $7)
    RETURNING id, auth_provider, auth_provider_id, email, role, status, kyc_status, created_at, updated_at
`

type CreateUserParams struct {
	ID             uuid.UUID
	AuthProvider   string
	AuthProviderID string
	Email          string
	Role           string
	Status         string
	KycStatus      string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (IdentityUser, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.AuthProvider,
		arg.AuthProviderID,
		arg.Email,
		arg.Role,
		arg.Status,
		arg.KycStatus,
	)
	var i IdentityUser
	err := row.Scan(
		&i.ID,
		&i.AuthProvider,
		&i.AuthProviderID,
		&i.Email,
		&i.Role,
		&i.Status,
		&i.KycStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByAuthProviderID = `-- name: GetUserByAuthProviderID :one
SELECT id, auth_provider, auth_provider_id, email, role, status, kyc_status, created_at, updated_at FROM identity.users WHERE auth_provider = $1 AND auth_provider_id = $2
`

type GetUserByAuthProviderIDParams struct {
	AuthProvider   string
	AuthProviderID string
}

func (q *Queries) GetUserByAuthProviderID(ctx context.Context, arg GetUserByAuthProviderIDParams) (IdentityUser, error) {
	row := q.db.QueryRow(ctx, getUserByAuthProviderID, arg.AuthProvider, arg.AuthProviderID)
	var i IdentityUser
	err := row.Scan(
		&i.ID,
		&i.AuthProvider,
		&i.AuthProviderID,
		&i.Email,
		&i.Role,
		&i.Status,
		&i.KycStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, auth_provider, auth_provider_id, email, role, status, kyc_status, created_at, updated_at FROM identity.users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (IdentityUser, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i IdentityUser
	err := row.Scan(
		&i.ID,
		&i.AuthProvider,
		&i.AuthProviderID,
		&i.Email,
		&i.Role,
		&i.Status,
		&i.KycStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserKYCStatus = `-- name: UpdateUserKYCStatus :one
UPDATE identity.users SET kyc_status = $2, updated_at = now() WHERE id = $1 RETURNING id, auth_provider, auth_provider_id, email, role, status, kyc_status, created_at, updated_at
`

type UpdateUserKYCStatusParams struct {
	ID        uuid.UUID
	KycStatus string
}

func (q *Queries) UpdateUserKYCStatus(ctx context.Context, arg UpdateUserKYCStatusParams) (IdentityUser, error) {
	row := q.db.QueryRow(ctx, updateUserKYCStatus, arg.ID, arg.KycStatus)
	var i IdentityUser
	err := row.Scan(
		&i.ID,
		&i.AuthProvider,
		&i.AuthProviderID,
		&i.Email,
		&i.Role,
		&i.Status,
		&i.KycStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserRole = `-- name: UpdateUserRole :one
UPDATE identity.users SET role = $2, updated_at = now() WHERE id = $1 RETURNING id, auth_provider, auth_provider_id, email, role, status, kyc_status, created_at, updated_at
`

type UpdateUserRoleParams struct {
	ID   uuid.UUID
	Role string
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (IdentityUser, error) {
	row := q.db.QueryRow(ctx, updateUserRole, arg.ID, arg.Role)
	var i IdentityUser
	err := row.Scan(
		&i.ID,
		&i.AuthProvider,
		&i.AuthProviderID,
		&i.Email,
		&i.Role,
		&i.Status,
		&i.KycStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
